// Editorial content belongs here; property support comes from the application's catalogs.
export const descriptions = {
  form: 'The root window. Give your app somewhere to live.', button: 'A clear call to action, with your logic behind the click.',
  label: 'Display text, results, and the occasional well-earned victory message.', textbox: 'Collect a single line of text. Bind it when you need the latest value.',
  searchbox: 'A text input styled for search. Your script decides what gets filtered.', passwordbox: 'An obscured text input. Presentation privacy, not encryption.',
  textarea: 'Room for paragraphs, notes, and words that refuse to fit on one line.', maskedtextbox: 'Guide input with a fixed character pattern.', richtextbox: 'Structured text with a compact formatting toolbar.',
  checkbox: 'A boolean choice that says exactly what it means.', radiobutton: 'One choice among sibling radio buttons.', toggleswitch: 'A switch for an on/off setting.', togglebutton: 'A button that remembers its checked state.',
  combobox: 'A compact dropdown for one choice.', listbox: 'An always-visible list with one selection.', listview: 'A list-style choice view. Use DataGridView for columns.', checkedlistbox: 'An item list with independent checkboxes.',
  radiogroup: 'One selection from a named collection of radio choices.', checkboxgroup: 'Several choices, one neatly grouped control.', segmentedcontrol: 'Switch between choices with a row of buttons.', buttongroup: 'A grouped set of single-selection buttons.', chipgroup: 'Multiple selected tags in a compact strip.',
  rating: 'A whole-star rating, with optional read-only display.', chip: 'A selectable pill that can also be dismissed.', iconbutton: 'An action represented by an icon and an accessible label.', floatingactionbutton: 'A circular action button for your primary task.', commandbutton: 'An icon, title, description, and a regular click action.',
  dropdownbutton: 'A trigger for a structured command menu.', splitbutton: 'One primary action plus a menu of alternatives.',
  numericupdown: 'A numeric value with minimum, maximum, and step controls.', slider: 'Choose a number by moving a thumb.', progressbar: 'Show progress along a line.', circularprogress: 'Show progress as a circular percentage.',
  datepicker: 'Choose a date without timezone conversions.', timepicker: 'Choose a local time in hours and minutes.', datetimepicker: 'Choose a local date and time.', colorpicker: 'Choose a color as a six-digit hex value.',
  image: 'Display an image selected in the Builder or set at runtime.', picturebox: 'An image display with configurable fitting behavior.', avatar: 'An image or initials for the person behind the data.', badge: 'A small status label with semantic color variants.', icon: 'Display one of Forma’s bundled icons.', divider: 'Create visual breathing room between sections.', emptystate: 'Explain why there is no content and what to do next.', spinner: 'Show that work is happening, without pretending to know the percentage.', skeleton: 'A placeholder while real content gets ready.',
  panel: 'A free-position container. Move the panel; its children come along.', groupbox: 'A titled container for related controls.', card: 'A content container with an optional header and description.', splitcontainer: 'Two panes with one-based child slot assignment.', tabcontrol: 'Multiple pages with horizontal or vertical tab headers.', flowlayoutpanel: 'Arrange children in order with orientation and spacing.', tablelayoutpanel: 'Place children in a grid of columns and rows.', accordion: 'Expandable sections with one active section at a time.',
  stackpanel: 'An ordered stack of controls, vertical by default.', hstack: 'A horizontal stack preset.', vstack: 'A vertical stack preset.', wrappanel: 'Flow children onto another row or column when space runs out.', centerpanel: 'Center a group of children in both directions.', sidebar: 'A vertical stack with scrolling, ready for navigation.', appshell: 'A responsive sidebar-and-content composition.', responsivepanel: 'Wrap at wide sizes and stack below a breakpoint.', scrollablepanel: 'Free-position content inside a scrollable viewport.',
  breadcrumb: 'A selectable path through your application.', sidenavigation: 'A single-selection navigation list. Your script handles the destination.',
  datagridview: 'A table of string cells with selection, sorting, filtering, and runtime edits.', treeview: 'Display expandable hierarchical data.', propertygrid: 'Display named property entries, optionally editable.', pagination: 'A page selector calculated from item count and page size.',
  filepicker: 'Open a native file chooser and read the selected path.', folderpicker: 'Open a native folder chooser and read the selected path.', linklabel: 'Open an absolute HTTP or HTTPS URL through the host.',
  menustrip: 'A structured top-level command menu.', toolbar: 'A compact collection of command actions.', toolstrip: 'A strip of structured commands.', statusbar: 'Display left and right status text.',
  timer: 'A nonvisual interval that raises Tick while enabled.', backgroundworker: 'A Core background-work component; JavaScript can inspect its status and flags.', toast: 'A transient notification shown from the component tray.', loadingoverlay: 'A tray service that covers its target while work runs.', tooltip: 'Attach delayed contextual help to a target control.', contextmenu: 'Attach a structured right-click menu to a target.', contextmenustrip: 'A context-menu variant with the same command model.', dialog: 'A modal message with configured buttons and a native result.', confirmationdialog: 'A confirmation dialog preset for consequential choices.',
};

const text = ['textbox','searchbox','passwordbox','textarea','maskedtextbox'];
const choices = ['combobox','listbox','listview','radiogroup','segmentedcontrol','buttongroup','breadcrumb','sidenavigation'];
const multi = ['checkedlistbox','checkboxgroup','chipgroup'];
const checks = ['checkbox','radiobutton','toggleswitch','togglebutton','chip'];
const numbers = ['numericupdown','slider','progressbar','circularprogress','rating'];
const commands = ['menustrip','toolbar','toolstrip','contextmenu','contextmenustrip','dropdownbutton','splitbutton'];
const layouts = ['flowlayoutpanel','stackpanel','hstack','vstack','wrappanel','centerpanel','sidebar','responsivepanel','appshell'];
export function recipe(kind) {
  const name = 'sample';
  if (text.includes(kind)) return { code: `const input = forma.bind("${name}", "value");\nforma.on("Input", () => {\n  console.log(input.value); // read now, not at startup\n});`, notes: 'Read live input with value; write it with text. A plain get at startup is a snapshot. MaskedTextBox retains underscores for incomplete slots.' };
  if (choices.includes(kind)) return { code: `const selection = forma.bind("sample", "selectedIndex");\nselection.subscribe(index => {\n  const items = forma.get("sample", "items");\n  console.log(index >= 0 ? items[index] : "No selection");\n});`, notes: 'Items are a string array in JavaScript and one item per line in the inspector. Indices are zero-based; -1 clears the selection. Navigation components raise navigate but do not load pages automatically.' };
  if (multi.includes(kind)) return { code: `const selected = forma.bind("sample", "checkedIndices");\nselected.subscribe(indices => console.log(indices));\nforma.on("Load", () => {\n  forma.set("sample", "items", ["Design", "Code", "Test"]);\n  forma.set("sample", "checkedIndices", [0, 2]);\n});`, notes: 'Pass arrays, not JSON strings. Checked indices are normalized to unique valid indices. The inspector accepts comma-separated indices.' };
  if (checks.includes(kind)) return { code: `const checked = forma.bind("sample", "checked");\nchecked.subscribe(value => console.log("Checked:", value));\nforma.on("Load", () => forma.set("sample", "checked", true));`, notes: kind === 'radiobutton' ? 'User selection groups sibling radio buttons by parent. Programmatic changes should explicitly update any other radio states you need to clear.' : kind === 'chip' ? 'Set removable to true to allow dismissal. chip-remove reports dismissal. Set isRemoved to false to restore it in the current Preview.' : 'Use booleans, not the strings "true" and "false".' };
  if (numbers.includes(kind)) return { code: `const amount = forma.bind("sample", "value");\namount.subscribe(value => console.log(value));\nforma.on("Load", () => {\n  forma.set("sample", "value", ${kind === 'rating' ? '4' : '50'});\n});`, notes: 'Values are numbers and clamp to the configured bounds. Rating uses whole stars. Progress controls display progress; your code supplies the value.' };
  if (layouts.includes(kind)) return { code: `forma.on("Load", () => {\n  forma.set("sample", "gap", 12);${['appshell','responsivepanel'].includes(kind) ? '\n  forma.set("sample", "breakpoint", 640);' : ''}\n});`, notes: 'Child order controls placement. Drag to reorder, rather than assigning free X/Y. Child width/height still affect layout. AppShell uses the first child as the sidebar at wide horizontal sizes; the breakpoint measures container width.' };
  if (commands.includes(kind)) return { code: `forma.on("Load", () => {\n  forma.set("sample", "commandItems", [\n    { id: "save", text: "Save" },\n    { id: "autosave", text: "Auto save", checkOnClick: true }\n  ]);\n});\nforma.on("command-item", event => {\n  console.log(event.detail.itemId, event.detail.checked);\n});${kind === 'splitbutton' ? '\nforma.on("primary-click", () => console.log("Primary action"));' : ''}`, notes: 'Command IDs identify actions. Use command-item for menu selections; a generic click also sees trigger clicks. Commands can include nested items, separators, enabled, checked, and checkOnClick.' };
  const examples = {
    form: ['forma.on("Load", () => {\n  forma.set("welcomeLabel", "text", "Let’s build something.");\n});', 'Add a Label named welcomeLabel. Form startup callbacks run after all component scripts are installed. main.js is separate from the form’s own script.js.'],
    button: ['forma.on("Click", () => {\n  const name = forma.get("nameInput", "value");\n  forma.set("greetingLabel", "text", `Hello, ${name}!`);\n});', 'Add a TextBox named nameInput and a Label named greetingLabel. Save the script and start a fresh Preview.'],
    label: ['forma.on("Load", () => {\n  forma.set("sample", "text", "Ready when you are.");\n  forma.set("sample", "fontSize", 24);\n});', 'Text is display content. Typography properties and custom CSS can both affect rendering.'],
    timer: ['let seconds = 0;\nforma.on("Tick", () => {\n  seconds++;\n  forma.set("countLabel", "text", String(seconds));\n});', 'Put Tick on the Timer’s own script, add a Label named countLabel, set interval to 1000, and enable the Timer in the inspector or from a Button. interval must be a number.'],
    toast: ['forma.on("Click", () => {\n  forma.showToast("sample", {\n    text: "Saved. Look at you go.",\n    variant: "success",\n    duration: 3000\n  });\n});', 'Put this handler on a Button, with a Toast named sample in the tray. Variants include neutral, info, success, warning, caution, error, and danger. error/danger use a red background with white text by default.'],
    loadingoverlay: ['forma.on("Click", async () => {\n  forma.set("sample", "isActive", true);\n  try {\n    await new Promise(resolve => setTimeout(resolve, 1000));\n  } finally {\n    forma.set("sample", "isActive", false);\n  }\n});', 'Put this on a Button. The overlay lives in the tray; choose its visual target with targetId. A finally block stops loading even when work fails.'],
    datagridview: ['forma.on("Load", () => {\n  forma.set("sample", "columns", ["Name", "Age"]);\n  forma.set("sample", "rows", [["Angel", "24"]]);\n});\nforma.on("row-selection", event => {\n  console.log("Original row index:", event.detail.row);\n});', 'Columns and cells must be strings. Use addRow/updateRow/removeRow/clearRows/setCell for sequential edits. Getters return copies; mutating a returned array does not edit the grid.'],
    tabcontrol: ['forma.on("Load", () => {\n  forma.set("sample", "tabs", ["Profile", "Settings", "About"]);\n  forma.set("sample", "orientation", "vertical");\n  forma.set("sample", "selectedTab", 1);\n});', 'Add pages with Add tab or Tabs in Properties. Select the destination page before dropping children. selectedTab is zero-based; child layoutSlot is one-based.'],
    accordion: ['forma.on("Load", () => {\n  forma.set("sample", "tabs", ["Account", "Preferences"]);\n  forma.set("sample", "selectedTab", 0);\n  forma.set("sample", "expanded", true);\n});\nforma.on("Change", event => console.log(event.detail));', 'Tabs are section names. Use Add section, select a section, and drop its children. Removing a section does not automatically relocate its children; adjust layoutSlot.'],
    tablelayoutpanel: ['forma.on("Load", () => {\n  forma.set("sample", "columns", 2);\n  forma.set("sample", "rowCount", 3);\n  forma.set("sample", "gap", 12);\n});', 'Rows use rowCount in runtime scripts. Assign children to one-based layoutSlot cells. The table manages X/Y; drag to change placement rather than free position.'],
    splitcontainer: ['forma.on("Load", () => {\n  forma.set("sample", "orientation", "horizontal");\n  forma.set("sample", "gap", 12);\n});', 'Horizontal means left/right panes; vertical means top/bottom. Assign children to layoutSlot 1 or 2. Dragging the splitter is not implemented yet.'],
    panel: ['forma.on("Load", () => {\n  forma.set("sample", "paddingLeft", 16);\n  forma.set("sample", "backColor", "#eef2ff");\n});', 'Drop children into the panel’s content area to group them. Free-position children can move/resize; Dock, Anchor, and managed parent layouts can constrain geometry.'],
    groupbox: ['forma.on("Load", () => forma.set("sample", "text", "Account details"));', 'The caption reserves header space. Child X/Y starts in the content area, below the header.'],
    card: ['forma.on("Load", () => {\n  forma.set("sample", "text", "Profile");\n  forma.set("sample", "description", "The person behind the pixels.");\n  forma.set("sample", "headerVisible", true);\n});', 'Use the header for a title and description. Place child controls in the content area.'],
    scrollablepanel: ['forma.on("Load", () => forma.set("sample", "scrollDirection", "vertical"));', 'Position content outside the visible viewport to create overflow. Choose both, horizontal, or vertical scrolling.'],
    spinner: ['forma.on("Load", () => {\n  forma.set("sample", "speed", 900);\n  forma.set("sample", "isActive", true);\n});', 'Speed is the animation duration in milliseconds, not an interval event. Respect reduced motion; switch isActive off when your work finishes.'],
    skeleton: ['forma.on("Load", () => {\n  forma.set("sample", "shape", "text");\n  forma.set("sample", "lines", 3);\n  forma.set("sample", "isActive", true);\n});', 'Lines affect the text shape. Rectangle and circle display one placeholder. Set visible or replace content when loading completes.'],
    badge: ['forma.on("Load", () => {\n  forma.set("sample", "text", "Approved");\n  forma.set("sample", "variant", "success");\n  forma.set("sample", "fontSize", 18);\n});', 'Badge uses danger for its red status variant. Toast additionally accepts error and caution.'],
    avatar: ['forma.on("Load", () => {\n  forma.set("sample", "initials", "AZ");\n  forma.set("sample", "shape", "circle");\n});', 'Choose Image in the inspector to set an image. For a dynamic image use source, not text. Initials are the fallback.'],
    image: ['// Put on a Button beside a FilePicker named photoPicker.\nforma.on("Click", () => {\n  const path = forma.get("photoPicker", "selectedPath");\n  if (path) forma.set("sample", "source", path);\n});', 'Choose the file with the native picker first. Use sizeMode contain, cover, or fill. Local design images are embedded when the project is saved.'],
    picturebox: ['forma.on("Load", () => forma.set("sample", "sizeMode", "contain"));', 'Use Choose Image in the inspector. Runtime source accepts an image source; text changes the caption/alternative text, not the image.'],
    filepicker: ['// Put on a Button after choosing a file.\nforma.on("Click", () => {\n  console.log(forma.get("sample", "selectedPath"));\n});', 'selectedPath is read-only to JavaScript. Configure dialogTitle and filter. Native selection happens in the desktop Preview; reading value/text is not the selected path API.'],
    folderpicker: ['// Put on a Button after choosing a folder.\nforma.on("Click", () => console.log(forma.get("sample", "selectedPath")));', 'selectedPath is read-only to JavaScript. The FolderPicker opens a native desktop chooser; there is no browser-only replacement in these docs.'],
    backgroundworker: ['const busy = forma.bind("sample", "isBusy");\nbusy.subscribe(value => console.log("Worker busy:", value));', 'isBusy is read-only. JavaScript can configure workerReportsProgress and workerSupportsCancellation, but cannot launch a Core worker delegate. In C# call RunAsync and CancelAsync.'],
    tooltip: ['forma.on("Load", () => {\n  forma.set("sample", "targetId", "nameInput");\n  forma.set("sample", "text", "Use your full name.");\n  forma.set("sample", "placement", "bottom");\n});', 'Add a TextBox named nameInput. This tray component targets a visual control; initialDelay and showDuration use milliseconds.'],
    dialog: ['// Put on a Button.\nforma.on("Click", () => forma.showDialog("sample"));', 'Configure message and buttons on the tray Dialog. result and isOpen are read-only status properties. showDialog does not return a promise containing the result.'],
    confirmationdialog: ['// Put on a Button.\nforma.on("Click", () => forma.showDialog("sample"));', 'Use for a confirmation message. Observe result with forma.bind or subscribe to the Core Closed event in a C# host.'],
    treeview: ['forma.on("Load", () => {\n  forma.set("sample", "nodes", [\n    { id: "project", text: "Project", children: [\n      { id: "source", text: "Source", children: [] }\n    ] }\n  ]);\n  forma.set("sample", "expandedNodes", ["project"]);\n});', 'Pass node objects with stable unique IDs, text, and optional children. expandedNodes is an array of node IDs; selectedNode is one ID.'],
    propertygrid: ['forma.on("Load", () => {\n  forma.set("sample", "entries", [\n    { name: "Theme", value: "Dark", category: "Appearance", readOnly: false }\n  ]);\n});', 'Entries use string names/values. This displays application data; it does not automatically bind to another component’s inspector.'],
    richtextbox: ['forma.on("Load", () => {\n  forma.set("sample", "document", [\n    { kind: "paragraph", runs: [\n      { text: "Hello ", bold: true }, { text: "Forma" }\n    ] }\n  ]);\n});', 'Use paragraph, bullet, or number blocks with text runs. Setting text replaces rich formatting. HTML/RTF import is not implemented.'],
    pagination: ['const page = forma.bind("sample", "page");\npage.subscribe(value => console.log("Page:", value));\nforma.on("Load", () => {\n  forma.set("sample", "totalItems", 250);\n  forma.set("sample", "pageSize", 25);\n});', 'page is one-based; pageCount is calculated and read-only. Pagination does not fetch or slice your data automatically.'],
    datepicker: ['forma.on("Load", () => forma.set("sample", "value", "2026-10-10"));', 'Use YYYY-MM-DD. Empty string clears the value. No timezone suffix.'],
    timepicker: ['forma.on("Load", () => forma.set("sample", "value", "13:15"));', 'Use HH:mm. Empty string clears the value.'],
    datetimepicker: ['forma.on("Load", () => forma.set("sample", "value", "2026-10-10T13:15"));', 'Use YYYY-MM-DDTHH:mm without a timezone suffix. This represents local date/time.'],
    colorpicker: ['forma.on("Load", () => forma.set("sample", "value", "#7c3aed"));', 'Use a six-digit hex string. Observe a value binding to react to user changes.'],
    linklabel: ['forma.on("Load", () => forma.set("sample", "url", "https://github.com/amabee/Forma"));', 'Only absolute HTTP and HTTPS URLs are accepted. Preview opens the native default browser.'],
    icon: ['forma.on("Load", () => {\n  forma.set("sample", "iconName", "search");\n  forma.set("sample", "strokeWidth", 2);\n});', 'Use names from the bundled icon selector; arbitrary remote SVG names are unsupported.'],
    emptystate: ['forma.on("Load", () => {\n  forma.set("sample", "text", "Nothing here. Yet.");\n  forma.set("sample", "description", "Create your first item to get started.");\n});', 'Explain both the missing content and the next step. Add a Button separately when the empty state needs an action.'],
    divider: ['forma.on("Load", () => {\n  forma.set("sample", "orientation", "horizontal");\n  forma.set("sample", "thickness", 2);\n  forma.set("sample", "lineStyle", "solid");\n});', 'Orientation, thickness, and lineStyle determine the line; geometry determines the space around it.'],
    statusbar: ['forma.on("Load", () => {\n  forma.set("sample", "text", "Ready");\n  forma.set("sample", "rightText", "3 items");\n});', 'This is a visual bar. Place/dock it in your form; it does not become the Builder’s own status bar.'],
  };
  if (['iconbutton','floatingactionbutton','commandbutton'].includes(kind)) return { code: 'forma.on("Click", () => console.log("Action fired"));', notes: 'Text supplies the accessible label even when showText is false. Use iconName from the bundled selector. FloatingActionButton stays at its designed position; use Anchor to pin it.' };
  if (!examples[kind]) throw new Error(`Missing component recipe: ${kind}`);
  return { code: examples[kind][0], notes: examples[kind][1] };
}
