import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright';

const origin = process.env.DOCS_PREVIEW_URL || 'http://127.0.0.1:4321';
const base = ('/' + (process.env.DOCS_BASE || '').replace(/^\/+|\/+$/g, '')).replace(/\/$/, '');
const channel = process.env.DOCS_BROWSER_CHANNEL || 'chrome';
const browser = await chromium.launch(channel === 'chromium' ? {} : { channel });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
fs.mkdirSync('dist/qa', { recursive: true });
try {
  await page.goto(origin + base + '/');
  await page.locator('#demo-name').fill('Angel');
  await page.getByRole('button', { name: 'Say hello' }).click();
  assert.equal(await page.locator('#demo-title').textContent(), 'Hey, Angel.');
  await page.locator('[data-source-tab="script"]').click();
  assert.equal(await page.locator('#source-script').isVisible(), true);
  assert.equal(await page.locator('#source-css').isVisible(), false);
  await page.locator('[data-source-tab="json"]').click();
  assert.ok((await page.locator('#source-json').textContent()).includes('clicks'));
  await page.locator('[data-source-tab="css"]').click();
  await page.locator('#theme-toggle').click();
  const theme = await page.locator('html').getAttribute('data-theme');
  await page.reload(); assert.equal(await page.locator('html').getAttribute('data-theme'), theme);
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
  await page.screenshot({ path: 'dist/qa/home-dark.png', fullPage: true });
  await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
  await page.screenshot({ path: 'dist/qa/home-light.png', fullPage: true });
  await page.goto(origin + base + '/components/');
  await page.locator('#component-filter').fill('filepicker');
  assert.equal(await page.locator('[data-component-name]:visible').count(), 1);
  await page.locator('[data-component-name]:visible').click();
  await page.getByRole('heading', { name: 'Runtime property API', exact: true }).waitFor();
  await page.locator('.copy-code').first().click();
  await page.waitForFunction(() => document.querySelector('.copy-code')?.textContent === 'Copied!');
  assert.ok((await page.evaluate(() => navigator.clipboard.readText())).includes('selectedPath'));
  await page.keyboard.press('Control+k');
  await page.locator('#search-input').fill('selectedPath');
  await page.locator('.search-result').first().waitFor();
  assert.ok((await page.locator('#search-results').textContent()).includes('FilePicker'));
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter');
  await page.waitForLoadState('networkidle');
  assert.ok(page.url().includes('/guides/') || page.url().includes('/components/'));
  await page.goto(origin + base + '/components/timer/');
  await page.screenshot({ path: 'dist/qa/timer-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(origin + base + '/');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.locator('#menu-toggle').click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'true');
  await page.locator("#sidebar .overview-link").first().waitFor({ state: "visible" });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'false');
  await page.screenshot({ path: 'dist/qa/home-mobile.png', fullPage: true });
  await page.goto(origin + base + '/components/datagridview/');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: 'dist/qa/grid-mobile.png', fullPage: true });
  await page.locator('[data-search-open]').click(); await page.locator('#search-input').fill('providers');
  await page.locator('.search-result').first().waitFor();
  await page.locator('#search-close').click();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: greeting, persisted theme, filtering, code copying, full-text search, keyboard navigation, and mobile layouts.');
} finally { await context.close(); await browser.close(); }
